applications:
  - name: Customer API
    prefix: cust
    path: /customers
    spec: test-data/link-example.yaml
  - name: Products API
    prefix: prod
    path: /products
    spec: test-data/api-with-examples.json
  - name: Marketing API
    prefix: mrk
    path: /marketing
    spec: test-data/petstore.json
  - name: Sales API
    prefix: sales
    path: /sales
    spec: test-data/openapi.yaml